name: pixelperks
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.3.3
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  flutter_wallpaper_manager: ^0.0.4
  flutter_native_splash: ^2.3.2
  eva_icons_flutter: ^3.1.0
  animated_text_kit: ^4.2.2
  circular_menu: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.1.14
  device_info_plus: ^9.0.3
  share_plus: ^7.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "/assets/icon/foreground-white.png"

flutter_native_splash:
  background_image: "assets/icon/splash-light.png"
  background_image_dark: "assets/icon/splash-dark.png"
  android: true
  ios: false
  web: false

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/thumbs/
    - .env

  